import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { wrapper, AppState } from '../store/store';
import { setRepositoriesData } from '../store/slices/repositorySlice';
import { useSelector } from 'react-redux';

export default function Home() {
  const { repositories } = useSelector((state: AppState) => state.repository);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>hola</h1>
        {repositories.map((repo: any) => (
          <div key={repo.id}>
            <h2>{repo.name}</h2>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <h1>footer</h1>
      </footer>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps((store) => async (): Promise<any> => {
  const resp = await fetch('https://api.github.com/users/ichrisdev/repos')
  const repositories = JSON.parse(JSON.stringify(await resp.json()));

  store.dispatch(setRepositoriesData(repositories));

})

